apiVersion: v1
kind: Service
metadata:
  name: banking-service
  namespace: banking-k8s-test
  labels:
    app: banking-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: banking-service