groups:
  - name: ddos_detection
    rules:
    - alert: DDoSDetectionHighScore
      expr: ddos_detection_score > 0.7
      for: 1m
      labels:
        severity: warning
        service: ddos-detection
      annotations:
        summary: "High DDoS detection score"
        description: "DDoS detection score is {{ $value }}"

    - alert: DDoSAttackDetected
      expr: ddos_binary_prediction == 1
      for: 30s
      labels:
        severity: critical
        service: ddos-detection
      annotations:
        summary: "DDoS attack detected"
        description: "ML model has detected a potential DDoS attack"

    - alert: ServiceDown
      expr: up == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Service {{ $labels.job }} is down"
        description: "Service {{ $labels.job }} has been down for more than 2 minutes"
