-- Create account database
CREATE DATABASE IF NOT EXISTS ACCOUNTDB;

USE ACCOUNTDB;

CREATE TABLE IF NOT EXISTS ACCOUNTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_NUMBER VARCHAR(20) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  BALANCE DECIMAL(15, 2) NOT NULL,
  TYPE VARCHAR(20) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ACCOUNTS (
  CUSTOMER_NUMBER,
  NAME,
  BALANCE,
  TYPE
) VALUES (
  'CUST001',
  'John Doe',
  5000.00,
  'Savings'
),
(
  'CUST002',
  'Jane Smith',
  12500.00,
  'Checking'
),
(
  'CUST003',
  'Bob Johnson',
  25000.00,
  'Investment'
);

-- Create transaction database
CREATE DATABASE IF NOT EXISTS TRANSACTIONDB;

USE TRANSACTIONDB;

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ACCOUNT_ID INT NOT NULL,
  AMOUNT DECIMAL(15, 2) NOT NULL,
  TYPE VARCHAR(20) NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO TRANSACTIONS (
  ACCOUNT_ID,
  AMOUNT,
  TYPE,
  STATUS
) VALUES (
  1,
  500.00,
  'DEPOSIT',
  'COMPLETED'
),
(
  2,
  -200.00,
  'WITHDRAWAL',
  'COMPLETED'
),
(
  1,
  -150.00,
  'PAYMENT',
  'COMPLETED'
);

-- Create auth database
CREATE DATABASE IF NOT EXISTS AUTHDB;

USE AUTHDB;

CREATE TABLE IF NOT EXISTS USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  PASSWORD VARCHAR(100) NOT NULL,
  ROLE VARCHAR(20) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USERS (
  USERNAME,
  PASSWORD,
  ROLE
) VALUES (
  'john.doe',
  'password123',
  'CUSTOMER'
),
(
  'jane.smith',
  'password456',
  'CUSTOMER'
),
(
  'admin',
  'admin123',
  'ADMIN'
);

-- Create fraud database
CREATE DATABASE IF NOT EXISTS FRAUDDB;

USE FRAUDDB;

CREATE TABLE IF NOT EXISTS FRAUD_ALERTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TRANSACTION_ID INT NOT NULL,
  ACCOUNT_ID INT NOT NULL,
  RISK_SCORE INT NOT NULL,
  TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);