version: '3.8'

services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.45
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
      - QUERY_BASE_PATH=/jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"
    networks:
      - banking-network

  # Trace Generator
  trace-generator:
    image: rishabhkumar2003/ddos-detection-banking-trace-generator:latest
    container_name: trace-generator
    ports:
      - "9414:9414"
    environment:
      - JAEGER_ENDPOINT=http://jaeger:4318/v1/traces
      - OTEL_SERVICE_NAME=trace-generator
    depends_on:
      - jaeger
    networks:
      - banking-network
