global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Core monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Banking services (with correct container names)
  - job_name: 'banking-services'
    static_configs:
      - targets: 
          - 'api-gateway:8080'
          - 'account-service:8081'
          - 'transaction-service:8082'
          - 'auth-service:8083'
          - 'notification-service:8084'
          - 'fraud-detection:8085'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Auto-baselining service
  - job_name: 'auto-baselining'
    static_configs:
      - targets: ['auto-baselining:5002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # DDoS ML Detection service (FIXED container name)
  - job_name: 'ddos-ml-detection'
    static_configs:
      - targets: ['ddos-ml-detection:5001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Transaction monitoring services

  - job_name: 'transaction-monitor'
    static_configs:
      - targets: ['transaction-performance-monitor:5003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'performance-aggregator'
    static_configs:
      - targets: ['performance-aggregator-service:5004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'anomaly-injector'
    static_configs:
      - targets: ['anomaly-injector-service:5005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Add this new job for trace-generator
  - job_name: 'trace-generator'
    static_configs:
      - targets: ['trace-generator:9414']
    metrics_path: '/metrics'
    scrape_interval: 10s



  # Windows IIS Monitoring
  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['mock-windows-exporter:9182']
    scrape_interval: 15s

  # - job_name: 'iis-application'
  #   static_configs:
  #     - targets: ['mock-iis-application:8090']
  #   metrics_path: '/metrics'
  #   scrape_interval: 10s

# Add these jobs to your existing prometheus.yml under scrape_configs:

# RabbitMQ Metrics
  - job_name: 'banking-rabbitmq'
    static_configs:
      - targets: ['banking-rabbitmq:15692']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Kafka Exporter Metrics
  - job_name: 'banking-kafka'
    static_configs:
      - targets: ['banking-kafka-exporter:9308']
    scrape_interval: 15s

  # Message Producer Service - FIXED PORT
  - job_name: 'banking-message-producer'
    static_configs:
      - targets: ['banking-message-producer:5007']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Message Consumer Service - FIXED PORT
  - job_name: 'banking-message-consumer'
    static_configs:
      - targets: ['banking-message-consumer:5008']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # DB Connection Demo Service - FIXED PORT
  - job_name: 'banking-db-demo'
    static_configs:
      - targets: ['banking-db-connection-demo:5006']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # PostgreSQL Exporter
  - job_name: 'banking-postgresql'
    static_configs:
      - targets: ['banking-postgres-exporter:9187']
    scrape_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets: []
