# Redis Cache Services Only - Quick Start
# This file starts only Redis-related services without container monitoring

services:
  # Redis Cache Server
  banking-redis:
    image: redis:7-alpine
    container_name: banking-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - banking-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Exporter for Prometheus
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: banking-redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://banking-redis:6379"
    depends_on:
      - banking-redis
    networks:
      - banking-network

  # Redis Cache Pattern Analyzer
  cache-pattern-analyzer:
    build: ./redis-cache-analyzer
    container_name: banking-cache-analyzer
    ports:
      - "5012:5012"
    environment:
      REDIS_HOST: banking-redis
      REDIS_PORT: 6379
      LOG_LEVEL: INFO
    depends_on:
      - banking-redis
    networks:
      - banking-network
    restart: unless-stopped

  # Redis Cache Load Generator
  cache-load-generator:
    build: ./redis-cache-load-generator
    container_name: banking-cache-load-generator
    ports:
      - "5013:5013"
    environment:
      REDIS_HOST: banking-redis
      REDIS_PORT: 6379
      LOG_LEVEL: INFO
    depends_on:
      - banking-redis
    networks:
      - banking-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  banking-network:
    name: ddos-detection-system_banking-network
    external: true