apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-service
  namespace: banking-k8s-test
  labels:
    app: banking-service
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-service
  template:
    metadata:
      labels:
        app: banking-service
        tier: application
    spec:
      containers:
      - name: banking-service
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: SERVICE_NAME
          value: "banking-service"
        - name: ENVIRONMENT
          value: "test"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5