apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-resource-monitor
  namespace: banking-k8s-test
  labels:
    app: k8s-resource-monitor
    tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-resource-monitor
  template:
    metadata:
      labels:
        app: k8s-resource-monitor
        tier: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9419"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: k8s-resource-monitor
        image: k8s-resource-monitor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9419
          name: metrics
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: TARGET_NAMESPACE
          value: "banking-k8s-test"
        - name: COLLECTION_INTERVAL
          value: "15"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9419
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9419
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-resource-monitor
  namespace: banking-k8s-test
  labels:
    app: k8s-resource-monitor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9419"
spec:
  type: ClusterIP
  ports:
  - port: 9419
    targetPort: 9419
    protocol: TCP
    name: metrics
  selector:
    app: k8s-resource-monitor